networks:
  registry-network:
    driver: bridge

services:
  # htpasswd 凭据生成器
  htpasswd-generator:
    container_name: htpasswd-generator
    image: httpd:2.4-alpine
    networks:
      - registry-network
    environment:
      - HTPASSWD_USERNAME=admin
      - HTPASSWD_PASSWORD=123456
    volumes:
      - ./auth:/tmp/auth
    command: >
      sh -c "
        htpasswd -bnBC 10 $${HTPASSWD_USERNAME} $${HTPASSWD_PASSWORD} > /tmp/auth/htpasswd &&
        echo 'Generated htpasswd for user: $${HTPASSWD_USERNAME}' &&
        cat /tmp/auth/htpasswd
      "
    restart: "no"

  # Docker Registry 核心服务
  registry:
    container_name: docker-registry
    image: registry:3.0.0
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - ./data:/var/lib/registry/docker/registry/v2
      - ./data-null:/var/lib/registry
      - ./auth/htpasswd:/auth/htpasswd:ro
    environment:
      TZ: Asia/Shanghai
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    depends_on:
      - htpasswd-generator

  # Registry 前端管理服务 (新开发的服务)
  registry-frontend:
    container_name: registry-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: Asia/Shanghai
      # Application settings
      SECRET_KEY: "change-this-secret-key-in-production"
      DEBUG: "false"
      # Registry connection
      REGISTRY_URL: http://docker-registry:5000
      REGISTRY_USERNAME: admin
      REGISTRY_PASSWORD: 123456
    volumes:
      # Mount database file for persistence
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - registry

  # Nginx 反向代理
  registry-nginx:
    container_name: registry-nginx
    image: nginx:latest
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - "30080:80"
      - "30443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 如果需要 SSL 证书，取消下面的注释并创建 ssl 目录
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - registry
      - registry-frontend

