networks:
  registry-network:
    driver: bridge

services:
  # Docker Registry 核心服务
  registry:
    container_name: docker-registry
    image: registry:3.0.0
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - ./data:/var/lib/registry/docker/registry/v2
      - ./data-null:/var/lib/registry
    environment:
      TZ: Asia/Shanghai
      REGISTRY_STORAGE_DELETE_ENABLED: true
      # No authentication - registry is internal only
      # All auth and permission checks handled by registry-manager proxy

  # Registry 前端管理服务 (新开发的服务)
  registry-manager:
    container_name: registry-manager
    image: registry-manager:test-v2.0
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: Asia/Shanghai
      # Application settings
      SECRET_KEY: "change-this-secret-key-in-production"
      DEBUG: "false"
      # Registry connection (no auth needed, internal communication)
      REGISTRY_URL: http://docker-registry:5000
    volumes:
      # Mount database file for persistence
      - ./data/db:/app/db
    depends_on:
      - registry

  # Nginx 反向代理
  registry-nginx:
    container_name: registry-nginx
    image: nginx:latest
    networks:
      - registry-network
    restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    ports:
      - "3081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 如果需要 SSL 证书，取消下面的注释并创建 ssl 目录
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - registry
      - registry-manager

